name: get_it_study
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.2
  go_router: ^14.6.2
  injectable: ^2.5.0
  injectable_generator: ^2.6.2

  # 상태관리
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  fluttertoast: ^8.2.8
  riverpod_annotation: ^2.6.1

  logger: ^2.5.0

  # 로컬 스토리지
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2

  # 데이터 모델링 및 직렬화
  freezed: ^2.5.7
  collection: ^1.18.0
  json_annotation: ^4.9.0
  intl: ^0.20.1
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf
    - family: Jalnan
      fonts:
        - asset: assets/fonts/JalnanTTF.ttf
    - family: JalnanGothic
      fonts:
        - asset: assets/fonts/JalnanGothicTTF.ttf
